version: "3"

services:
  backend:
    build: .
    image: r_2_r:latest
    container_name: ragToriches-1
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - database
      - redis
      - storage
    ports:
      - 8000:8000

  database:
    image: postgres:alpine3.20
    container_name: r_2_r_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  storage:
    platform: linux/amd64
    image: minio/minio:latest
    command: minio server /var/lib/minio/data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - storage:/var/lib/minio/data

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  celery:
    build: .
    image: ragToriches_celery
    container_name: r_2_r_celery
    command: celery -A ragToriches worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - backend

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

volumes:
  postgres_data:
  storage:


