# Generated by Django 5.1.1 on 2024-10-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
